repos:
  - repo: local
    hooks:
      ##########################
      #       FORMATTERS       #
      ##########################
      -   id: black
          name: black
          description: Format Python code
          language: system
          types: [python]
          entry: black
          exclude: |
            (?x)^(
                .git/.*|
                docs/.*|
                .venv/.*
            )$
      -   id: isort
          name: isort
          description: Format Python import statements
          language: system
          types: [python]
          entry: isort
          exclude: |
            (?x)^(
                .git/.*|
                docs/.*|
                .venv/.*
            )$

      ##########################
      #        LINTERS         #
      ##########################
    #   -   id: mypy
    #       name: mypy
    #       description: Enforce correct python type hints
    #       language: system
    #       types: [python]
    #       entry: mypy
      -   id: flake8
          name: flake8
          description: Enforce PEP8 Python Style Guide
          language: system
          types: [python]
          entry: flake8
          exclude: |
            (?x)^(
                .git/.*|
                docs/.*|
                .venv/.*
            )$

      ##########################
      #        STANDARD        #
      ##########################
      -   id: check-added-large-files
          name: check for added large files
          description: prevents giant files from being committed.
          entry: check-added-large-files
          language: system
          stages: [pre-commit, pre-push, manual]
          minimum_pre_commit_version: 3.2.0
          args: ['--maxkb=500000']
      -   id: check-ast
          name: check python ast
          description: simply checks whether the files parse as valid python.
          entry: check-ast
          language: system
          types: [python]
      -   id: check-merge-conflict
          name: check for merge conflicts
          description: checks for files that contain merge conflict strings.
          entry: check-merge-conflict
          language: system
          types: [text]
      -   id: check-toml
          name: check toml
          description: checks toml files for parseable syntax.
          entry: check-toml
          language: system
          types: [toml]
      -   id: end-of-file-fixer
          name: fix end of files
          description: ensures that a file is either empty, or ends with one newline.
          entry: end-of-file-fixer
          language: system
          types: [text]
          stages: [pre-commit, pre-push, manual]
          minimum_pre_commit_version: 3.2.0
      -   id: no-commit-to-branch
          name: "don't commit to branch"
          entry: no-commit-to-branch
          language: system
          pass_filenames: false
          always_run: true
          args: [--branch, master, --branch, staging, --branch, dev]
      -   id: trailing-whitespace
          name: trim trailing whitespace
          description: trims trailing whitespace.
          entry: trailing-whitespace-fixer
          language: system
          types: [text]
          stages: [pre-commit, pre-push, manual]
          minimum_pre_commit_version: 3.2.0
